name: CI

on: [push, pull_request]

jobs:
    tests:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Run composer install
              run: composer install
            - name: Run tests
              run: ./vendor/bin/phpunit

    php-cs-fixer:
        name: PHP-CS-Fixer
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: PHP-CS-Fixer
              uses: docker://oskarstark/php-cs-fixer-ga
              with:
                  args: src tests
